events {}

http {

    server {

        listen 80;

        location /auth/ {

            proxy_pass http://auth-service:5000;

        }

        location /files/ {

            proxy_pass http://file-service:5001;

        }

    }

}