events {}

http {

    server {

        listen 80;
        server_name secure-edge-gateway-vn.duckdns.org

        location /auth/ {

            proxy_pass http://auth-service:5000;

        }

        location /files/ {

            proxy_pass http://file-service:5001;

        }

    }

}